In [4]:
pip install pandas

Requirement already satisfied: pandas in C:\Users\User\miniconda3\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\User\miniconda3\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\User\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\User\miniconda3\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\User\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

In [8]:
s = pd.Series([1,2,3,4,5,6])

In [9]:
s.values

array([1, 2, 3, 4, 5, 6])

In [10]:
s[3]

np.int64(4)

In [12]:
s = pd.Series([15,20,12,16,10,11,12,15,9,10,12,17], index = ['jan','fev', 'mar', 'abr', 'mai', 'jun','jul', 'ago', 'set','out','nov', 'dez'])

In [15]:
s['jan']

np.int64(15)

In [16]:
s[0:6]

jan    15
fev    20
mar    12
abr    16
mai    10
jun    11
dtype: int64

In [17]:
s.mean()

np.float64(13.25)

In [18]:
s.describe()

count    12.000000
mean     13.250000
std       3.333712
min       9.000000
25%      10.750000
50%      12.000000
75%      15.250000
max      20.000000
dtype: float64

In [19]:
s[6:].mean()

np.float64(12.5)

In [22]:
df = pd.DataFrame({'Aluno' : ['Marina','Felipe','Cleyton','Isabel'],
'Créditos cursados': [20,64,32,24],
'Rendimento acadêmico' : [8.55,7.88,8.17,9.04],
'Mês de nascimento' : ['Novembro','Setembro','Janeiro','Julho'],
'Curso': ['Computação','Estatística','Computação','Matemática']})

In [23]:
df.iloc[2]

Aluno                      Cleyton
Créditos cursados               32
Rendimento acadêmico          8.17
Mês de nascimento          Janeiro
Curso                   Computação
Name: 2, dtype: object

In [24]:
df['Rendimento acadêmico'].mean()

np.float64(8.41)

In [25]:
df.describe()

       Créditos cursados  Rendimento acadêmico
count           4.000000              4.000000
mean           35.000000              8.410000
std            19.966639              0.501664
min            20.000000              7.880000
25%            23.000000              8.097500
50%            28.000000              8.360000
75%            40.000000              8.672500
max            64.000000              9.040000

In [26]:
df=pd.read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv')

In [29]:
df.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,0,0,0,0.0
1,Albania,89,132,54,4.9
2,Algeria,25,0,14,0.7
3,Andorra,245,138,312,12.4
4,Angola,217,57,45,5.9
5,Antigua & Barbuda,102,128,45,4.9
6,Argentina,193,25,221,8.3
7,Armenia,21,179,11,3.8
8,Australia,261,72,212,10.4
9,Austria,279,75,191,9.7

In [30]:
df[df['country'] == 'Brazil']

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
23,Brazil,245,145,16,7.2

In [31]:
df[df['total_litres_of_pure_alcohol'] >= 12]

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
3,Andorra,245,138,312,12.4
15,Belarus,142,373,42,14.4
98,Lithuania,343,244,56,12.9

In [46]:
df.sort_values(by='beer_servings', ascending = False).head()

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
117,Namibia,376,3,1,6.8
45,Czech Republic,361,170,134,11.8
62,Gabon,347,98,59,8.9
65,Germany,346,117,175,11.3
98,Lithuania,343,244,56,12.9